[package]
name = "hyber-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
hyber-auth = { path = "../hyber-auth" }
hyber-core = { path = "../hyber-core" }
hyber-object = { path = "../hyber-object" }
hyber-handle = { path = "../hyber-handle" }
hyber-namespace = { path = "../hyber-namespace" }
hyber-vfs = { path = "../hyber-vfs" }
hyber-process = { path = "../hyber-process" }
hyber-ipc = { path = "../hyber-ipc" }
hyber-layout = { path = "../hyber-layout" }
hyber-manifest = { path = "../hyber-manifest" }

mlua = { version = "0.9", features = ["lua54", "vendored"] }
